major:

  domain: majorcineplex.com
  link_types: absolute
  parsing:
    page: http://www.majorcineplex.com/en/main
    encoding: utf-8
    elements: '.allMovies .eachMovie'
    rules:
      name:  css('.nameMovie a .nameMovieEn').first.text.strip
      international_name: css('.nameMovie a .nameMovieEn').first.text.strip
      link:  css('.nameMovie a').first.attr('href')
      cover: css('.poster a img').first.attr('src')
      date:  css('.nameMovie p.releaseDate').first.text